source 'https://rubygems.org'

gem 'rails', '4.0.4'
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

gem 'rails_admin'

gem 'unicorn'

gem 'mongoid', '~> 4.0.0'

# Resque
gem 'resque', require: 'resque/server'
gem 'resque-scheduler'

group :doc do
  gem 'sdoc', require: false
end


group :test, :development do
  gem 'rspec-rails'
  # Use debugger
  gem 'byebug'
end

group :tools do
  gem 'capistrano', '< 3.0.0'
  gem "net-ssh" , "2.7.0"
end

gem 'rvm-capistrano'
